export const host = "http://staging.php-dev.in:8844/trainingapp/api/"
export const login = "users/login"
export const register = "users/register"
export const forgot = "users/forgot"
export const change = "users/change"
export const update = "users/update"
export const fAccDetails = "users/getUserData"
export const productListing = "products/getList"